##Step 1: Setup and Created TWO Datasets

In [1]:
import pandas as pd

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 5],
    'name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Rohan'],
    'city': ['Nagpur', 'Pune', 'Mumbai', 'Nagpur', 'Nashik']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105, 106],
    'customer_id': [1, 2, 2, 6, 3, 1],
    'amount': [500, 1200, 300, 800, 950, 400]
})

print(customers)
print(orders)

   customer_id   name    city
0            1   Amit  Nagpur
1            2  Priya    Pune
2            3  Rahul  Mumbai
3            4  Sneha  Nagpur
4            5  Rohan  Nashik
   order_id  customer_id  amount
0       101            1     500
1       102            2    1200
2       103            2     300
3       104            6     800
4       105            3     950
5       106            1     400

##Step 2: merge() ( SAME as SQL JOIN )

In [9]:
# Inner: fakt matching rows
inner = pd.merge(customers, orders, on='customer_id', how='inner')
print(inner, sep='\n\n')

   customer_id   name    city  order_id  amount
0            1   Amit  Nagpur       101     500
1            1   Amit  Nagpur       106     400
2            2  Priya    Pune       102    1200
3            2  Priya    Pune       103     300
4            3  Rahul  Mumbai       105     950

In [5]:
# Left: sagle customers, order nasel tar NaN
left = pd.merge(customers, orders, on='customer_id', how='left')
print(left, sep='\n\n')

   customer_id   name    city  order_id  amount
0            1   Amit  Nagpur     101.0   500.0
1            1   Amit  Nagpur     106.0   400.0
2            2  Priya    Pune     102.0  1200.0
3            2  Priya    Pune     103.0   300.0
4            3  Rahul  Mumbai     105.0   950.0
5            4  Sneha  Nagpur       NaN     NaN
6            5  Rohan  Nashik       NaN     NaN

In [6]:
# Right: sagle orders
right = pd.merge(customers, orders, on='customer_id', how='right')
print(right, sep='\n\n')

   customer_id   name    city  order_id  amount
0            1   Amit  Nagpur       101     500
1            2  Priya    Pune       102    1200
2            2  Priya    Pune       103     300
3            6    NaN     NaN       104     800
4            3  Rahul  Mumbai       105     950
5            1   Amit  Nagpur       106     400

In [7]:
# Outer: donhi kadche sagle rows
outer = pd.merge(customers, orders, on='customer_id', how='outer', indicator=True)

print(outer, sep='\n\n')

   customer_id   name    city  order_id  amount      _merge
0            1   Amit  Nagpur     101.0   500.0        both
1            1   Amit  Nagpur     106.0   400.0        both
2            2  Priya    Pune     102.0  1200.0        both
3            2  Priya    Pune     103.0   300.0        both
4            3  Rahul  Mumbai     105.0   950.0        both
5            4  Sneha  Nagpur       NaN     NaN   left_only
6            5  Rohan  Nashik       NaN     NaN   left_only
7            6    NaN     NaN     104.0   800.0  right_only

##If Different Column Name

In [10]:
pd.merge(customers, orders, left_on='customer_id', right_on='customer_id')

   customer_id   name    city  order_id  amount
0            1   Amit  Nagpur       101     500
1            1   Amit  Nagpur       106     400
2            2  Priya    Pune       102    1200
3            2  Priya    Pune       103     300
4            3  Rahul  Mumbai       105     950

##Step 3: join() (index based)

In [11]:
cust_idx = customers.set_index('customer_id')
ord_idx = orders.set_index('customer_id')

joined = cust_idx.join(ord_idx, how='left')
print(joined)

              name    city  order_id  amount
customer_id
1             Amit  Nagpur     101.0   500.0
1             Amit  Nagpur     106.0   400.0
2            Priya    Pune     102.0  1200.0
2            Priya    Pune     103.0   300.0
3            Rahul  Mumbai     105.0   950.0
4            Sneha  Nagpur       NaN     NaN
5            Rohan  Nashik       NaN     NaN

In [12]:
cust_idx.join(ord_idx, how='inner', lsuffix='_cust', rsuffix='_ord')

              name    city  order_id  amount
customer_id
1             Amit  Nagpur       101     500
1             Amit  Nagpur       106     400
2            Priya    Pune       102    1200
2            Priya    Pune       103     300
3            Rahul  Mumbai       105     950

##Step 4: concat() (stack)
##a Vertical (rows khali add)

In [13]:
new_customers = pd.DataFrame({
    'customer_id': [6, 7],
    'name': ['Neha', 'Karan'],
    'city': ['Delhi', 'Nagpur']
})

all_customers = pd.concat([customers, new_customers], ignore_index=True)
print(all_customers)

   customer_id   name    city
0            1   Amit  Nagpur
1            2  Priya    Pune
2            3  Rahul  Mumbai
3            4  Sneha  Nagpur
4            5  Rohan  Nashik
5            6   Neha   Delhi
6            7  Karan  Nagpur

##b Horizontal (columns shejari)

In [14]:
side_by_side = pd.concat([customers, orders], axis=1)
print(side_by_side)

   customer_id   name    city  order_id  customer_id  amount
0          1.0   Amit  Nagpur       101            1     500
1          2.0  Priya    Pune       102            2    1200
2          3.0  Rahul  Mumbai       103            2     300
3          4.0  Sneha  Nagpur       104            6     800
4          5.0  Rohan  Nashik       105            3     950
5          NaN    NaN     NaN       106            1     400

##(c) keys vapra (konta data konkadcha kalayla)

In [15]:
pd.concat([customers, new_customers], keys=['old', 'new'])

       customer_id   name    city
old 0            1   Amit  Nagpur
    1            2  Priya    Pune
    2            3  Rahul  Mumbai
    3            4  Sneha  Nagpur
    4            5  Rohan  Nashik
new 0            6   Neha   Delhi
    1            7  Karan  Nagpur

##Step 6: Extra practice

In [16]:
# Merge nantar analysis
merged = pd.merge(customers, orders, on='customer_id', how='inner')

# Total amount per city
print(merged.groupby('city')['amount'].sum())

# Konte customers ni kahich order kele nahit?
no_orders = pd.merge(customers, orders, on='customer_id', how='left', indicator=True)
print(no_orders[no_orders['_merge'] == 'left_only'])

city
Mumbai     950
Nagpur     900
Pune      1500
Name: amount, dtype: int64
   customer_id   name    city  order_id  amount     _merge
5            4  Sneha  Nagpur       NaN     NaN  left_only
6            5  Rohan  Nashik       NaN     NaN  left_only