In [1]:
import pandas as pd

##Step 2 — Pandas Series

In [2]:
marks = pd.Series([75,82,68,90,85])
print(marks)

0    75
1    82
2    68
3    90
4    85
dtype: int64

##Step 3 — Pandas DataFrame

In [1]:
import pandas as pd 

data = {
    "Name": ["Amit","Priya","Rahul","Sneha","Neha"],
    "Age": [22,23,24,21,25],
    "Marks": [75,82,68,90,85],
    "City":["Nagpur","Pune","Mumbai","Nagpur","Pune"]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks    City
0   Amit   22     75  Nagpur
1  Priya   23     82    Pune
2  Rahul   24     68  Mumbai
3  Sneha   21     90  Nagpur
4   Neha   25     85    Pune

##Step 4 — head() Function

In [2]:
df.head()

    Name  Age  Marks    City
0   Amit   22     75  Nagpur
1  Priya   23     82    Pune
2  Rahul   24     68  Mumbai
3  Sneha   21     90  Nagpur
4   Neha   25     85    Pune

In [3]:
df.head(3)

    Name  Age  Marks    City
0   Amit   22     75  Nagpur
1  Priya   23     82    Pune
2  Rahul   24     68  Mumbai

##Step 5 — info() Function

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
 3   City    5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

##Step 6 — describe() Function

In [5]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   23.000000  80.000000
std     1.581139   8.631338
min    21.000000  68.000000
25%    22.000000  75.000000
50%    23.000000  82.000000
75%    24.000000  85.000000
max    25.000000  90.000000

In [6]:
df.describe(include="object")

C:\Users\khond\AppData\Local\Temp\ipykernel_10628\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

        Name    City
count      5       5
unique     5       3
top     Amit  Nagpur
freq       1       2