In [2]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\khond\appdata\roaming\python\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\khond\appdata\roaming\python\python313\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

##Step 2: Real dataset download

In [4]:
df =pd.read_csv(r"C:\Users\khond\OneDrive\Desktop\Python Internship Task\Excel_Internship_Task.csv")
df.head()

,Employee_ID,Employee_Name,Gender,Age,Department,Job_Title,City,State,Joining_Date,Salary,Performance_Score,Bonus,Employment_Status,Grade
0,10001,Pooja Deshmukh,Female,27,Sales,Sales Executive,Pune,Maharashtra,2024-10-17 00:00:00,45000,97,6167.77,Active,D
1,10002,Rohit Deshmukh,Female,33,Sales,Sales Executive,Nagpur,Maharashtra,2025-01-06 00:00:00,33000,91,3767.25,Inactive,B
2,10003,Aarav Kadam,Male,42,IT,Software Developer,Delhi,Delhi,2022-07-24 00:00:00,62000,59,3461.93,Inactive,A
3,10004,Kavya Kulkarni,Male,23,HR,HR Executive,Pune,Maharashtra,2025-02-03 00:00:00,36000,79,3396.51,Inactive,A
4,10005,Isha Kulkarni,Female,25,Finance,Financial Analyst,Indore,Madhya Pradesh,2021-04-04 00:00:00,80000,92,4587.82,Inactive,A

In [5]:
print(df.shape)
df.info

(2500, 14)

<bound method DataFrame.info of       Employee_ID   Employee_Name  Gender  Age        Department  \
0           10001  Pooja Deshmukh  Female   27             Sales
1           10002  Rohit Deshmukh  Female   33             Sales
2           10003     Aarav Kadam    Male   42                IT
3           10004  Kavya Kulkarni    Male   23                HR
4           10005   Isha Kulkarni  Female   25           Finance
...           ...             ...     ...  ...               ...
2495        12496  Meera Deshmukh    Male   27                IT
2496        12497    Anjali Patil  Female   51  Customer Support
2497        12498    Rahul Jadhav  Female   41         Marketing
2498        12499      Kavya More  Female   43         Marketing
2499        12500    Pooja Chavan  Female   39           Finance

                Job_Title       City           State         Joining_Date  \
0         Sales Executive       Pune     Maharashtra  2024-10-17 00:00:00
1         Sales Executive     Nagpur     Maharashtra  2025-01-06 00:00:00
2      Software Developer      Delhi           Delhi  2022-07-24 00:00:00
3            HR Executive       Pune     Maharashtra  2025-02-03 00:00:00
4       Financial Analyst     Indore  Madhya Pradesh  2021-04-04 00:00:00
...                   ...        ...             ...                  ...
2495   Software Developer  Hyderabad       Telangana  2023-06-12 00:00:00
2496    Support Executive  Hyderabad       Telangana  2025-08-20 00:00:00
2497  Marketing Executive     Nashik     Maharashtra  2025-11-07 00:00:00
2498  Marketing Executive  Bengaluru       Karnataka  2023-05-15 00:00:00
2499    Financial Analyst     Nashik     Maharashtra  2021-11-23 00:00:00

      Salary  Performance_Score    Bonus Employment_Status Grade
0      45000                 97  6167.77            Active     D
1      33000                 91  3767.25          Inactive     B
2      62000                 59  3461.93          Inactive     A
3      36000                 79  3396.51          Inactive     A
4      80000                 92  4587.82          Inactive     A
...      ...                ...      ...               ...   ...
2495   78000                 55  3338.74          On Leave     D
2496   41000                 74  3387.62          On Leave     B
2497   58000                 51  4056.56          On Leave     B
2498   48000                 70  3972.85            Active     C
2499   55000                 74  4291.19            Active     A

[2500 rows x 14 columns]>

In [6]:
print(df.shape)
df.info

(2500, 14)

<bound method DataFrame.info of       Employee_ID   Employee_Name  Gender  Age        Department  \
0           10001  Pooja Deshmukh  Female   27             Sales
1           10002  Rohit Deshmukh  Female   33             Sales
2           10003     Aarav Kadam    Male   42                IT
3           10004  Kavya Kulkarni    Male   23                HR
4           10005   Isha Kulkarni  Female   25           Finance
...           ...             ...     ...  ...               ...
2495        12496  Meera Deshmukh    Male   27                IT
2496        12497    Anjali Patil  Female   51  Customer Support
2497        12498    Rahul Jadhav  Female   41         Marketing
2498        12499      Kavya More  Female   43         Marketing
2499        12500    Pooja Chavan  Female   39           Finance

                Job_Title       City           State         Joining_Date  \
0         Sales Executive       Pune     Maharashtra  2024-10-17 00:00:00
1         Sales Executive     Nagpur     Maharashtra  2025-01-06 00:00:00
2      Software Developer      Delhi           Delhi  2022-07-24 00:00:00
3            HR Executive       Pune     Maharashtra  2025-02-03 00:00:00
4       Financial Analyst     Indore  Madhya Pradesh  2021-04-04 00:00:00
...                   ...        ...             ...                  ...
2495   Software Developer  Hyderabad       Telangana  2023-06-12 00:00:00
2496    Support Executive  Hyderabad       Telangana  2025-08-20 00:00:00
2497  Marketing Executive     Nashik     Maharashtra  2025-11-07 00:00:00
2498  Marketing Executive  Bengaluru       Karnataka  2023-05-15 00:00:00
2499    Financial Analyst     Nashik     Maharashtra  2021-11-23 00:00:00

      Salary  Performance_Score    Bonus Employment_Status Grade
0      45000                 97  6167.77            Active     D
1      33000                 91  3767.25          Inactive     B
2      62000                 59  3461.93          Inactive     A
3      36000                 79  3396.51          Inactive     A
4      80000                 92  4587.82          Inactive     A
...      ...                ...      ...               ...   ...
2495   78000                 55  3338.74          On Leave     D
2496   41000                 74  3387.62          On Leave     B
2497   58000                 51  4056.56          On Leave     B
2498   48000                 70  3972.85            Active     C
2499   55000                 74  4291.19            Active     A

[2500 rows x 14 columns]>

##Next step TO_EXCEL()

In [7]:
df.to_excel("Employee_Output.xlsx",index=False)

In [14]:
df_excel = pd.read_excel("Employee_Output.xlsx")
df_excel.head()

,Employee_ID,Employee_Name,Gender,Age,Department,Job_Title,City,State,Joining_Date,Salary,Performance_Score,Bonus,Employment_Status,Grade
0,10001,Pooja Deshmukh,Female,27,Sales,Sales Executive,Pune,Maharashtra,2024-10-17 00:00:00,45000,97,6167.77,Active,D
1,10002,Rohit Deshmukh,Female,33,Sales,Sales Executive,Nagpur,Maharashtra,2025-01-06 00:00:00,33000,91,3767.25,Inactive,B
2,10003,Aarav Kadam,Male,42,IT,Software Developer,Delhi,Delhi,2022-07-24 00:00:00,62000,59,3461.93,Inactive,A
3,10004,Kavya Kulkarni,Male,23,HR,HR Executive,Pune,Maharashtra,2025-02-03 00:00:00,36000,79,3396.51,Inactive,A
4,10005,Isha Kulkarni,Female,25,Finance,Financial Analyst,Indore,Madhya Pradesh,2021-04-04 00:00:00,80000,92,4587.82,Inactive,A

In [12]:
active_emp = df[df["Employment_Status"] == "Active"]
active_emp.to_csv("Active_Employees.csv", index=False)

In [13]:
pd.read_csv("Active_Employees.csv").head()

,Employee_ID,Employee_Name,Gender,Age,Department,Job_Title,City,State,Joining_Date,Salary,Performance_Score,Bonus,Employment_Status,Grade
0,10001,Pooja Deshmukh,Female,27,Sales,Sales Executive,Pune,Maharashtra,2024-10-17 00:00:00,45000,97,6167.77,Active,D
1,10010,Kavya Deshmukh,Female,53,HR,HR Executive,Ahmedabad,Gujarat,2023-10-08 00:00:00,55000,55,6638.16,Active,B
2,10013,Neha More,Female,40,IT,Software Developer,Aurangabad,Maharashtra,2025-09-20 00:00:00,93000,90,8455.52,Active,B
3,10016,Meera Kadam,Male,54,Operations,Operations Executive,Mumbai,Maharashtra,2025-11-22 00:00:00,60000,88,4846.59,Active,B
4,10017,Karan More,Male,28,HR,HR Executive,Aurangabad,Maharashtra,2022-05-23 00:00:00,53000,64,1997.20,Active,B

In [15]:
df = pd.read_csv(r"C:\Users\khond\OneDrive\Desktop\Python Internship Task\Excel_Internship_Task.csv")

In [16]:
import os 
print(os.listdir())

['Active_Employees.csv', 'Employee_Output.xlsx', 'Excel_Internship_Task.csv', 'student.csv', 'student.txt', 'TASK 1 Report Complete.pdf', 'TASK 1.docx', 'TAsk 2 report complete.pdf', 'TAsk 2 report.docx', 'TASK 2.ipynb', 'Task 3 Report Complete.pdf', 'Task 3 Report.docx', 'TASK 3.ipynb', 'TASK 4 Report Complete.pdf', 'TASK 4.docx', 'TASK 4.ipynb', 'TASK 5 report complete.pdf', 'TASK 5 report.docx', 'TASK 5.ipynb', 'TASK 6 Report Complete.pdf', 'TASK 6.docx', 'TASK 6.ipynb', 'TASK 7 Report complete.pdf', 'TASK 7 Report.docx', 'TASK 7.ipynb', 'TASK 8.ipynb', 'Task1.ipynb', 'Task1.py', 'titanic.csv']